language: perl
arch:
  - arm64
matrix:
  include:
    - dist: xenial
      perl: 5.24
    - dist: bionic
      perl: 5.26
    - dist: focal
      perl: 5.32

#    - perl: "5.30"
#      dist: xenial
#    - perl: "5.28"
#      dist: xenial
#    - perl: "5.22"
#      dist: xenial
#    - perl: "5.20"
#      dist: trusty
#    - perl: "5.18"
#      dist: trusty
#    - perl: "5.16"
#      dist: trusty
#    - perl: "5.14"
#      dist: trusty
#    - perl: "5.12"
#      dist: trusty
#    - perl: "5.10"
#      dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install cpanminus; fi
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cpanm --sudo --quiet --installdeps --notest .; else if ! cpanm --quiet --installdeps --notest .; then cat ~/.cpanm/work/*/build.log; false; fi; fi

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/
sudo: false
