name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'

jobs:

  test_on_host:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       include:
         - os:                       'ubuntu-20.04'
         - os:                       'ubuntu-18.04'
         - os:                       'ubuntu-16.04'
    steps:
    - name: apt hacks
      # /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update -qq
      if: "startsWith(matrix.os, 'ubuntu-')"
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        set -e
        sudo apt-get install -q --no-install-recommends cpanminus
        # XXX need to manually install configure_requires deps --- META.* does not exist at this point and cannot be generated
        cpanm --sudo --quiet --notest File::ShareDir::Install
        cpanm --sudo --quiet --notest --installdeps .
        perl Makefile.PL
        make distcheck
        HARNESS_OPTIONS=j4:c make disttest
      if: "!startsWith(matrix.os,'windows-')"
