name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'
  pull_request:

jobs:

  test_on_host:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       include:
         - os:                       'ubuntu-20.04'
         - os:                       'ubuntu-18.04'
         - os:                       'ubuntu-16.04'
    steps:
    - name: apt hacks
      # /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update -qq
      if: "startsWith(matrix.os, 'ubuntu-')"
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        set -e
        sudo apt-get install -q --no-install-recommends cpanminus
        # XXX need to manually install configure_requires deps --- META.* does not exist at this point and cannot be generated
        cpanm --sudo --quiet --notest File::ShareDir::Install
        cpanm --sudo --quiet --notest --installdeps .
        perl Makefile.PL
        make distcheck
        HARNESS_OPTIONS=j4:c make disttest
      if: "!startsWith(matrix.os,'windows-')"

  test_in_container:
    name: Test with perl ${{ matrix.perlimage }}
    runs-on: ubuntu-latest
    container: perl:${{ matrix.perlimage }}
    strategy:
      matrix:
        include:
## some dependencies do not work with older perls
#          - perlimage: 5.10.1-buster
          - perlimage: 5.12.5-stretch
          - perlimage: 5.14.4-stretch
          - perlimage: 5.16.3-buster
          - perlimage: 5.18.4-buster
          - perlimage: 5.22.4-stretch

    steps:
    - uses: actions/checkout@v2
    - name: "build and test"
      run: |
        cpanm --quiet --notest File::ShareDir::Install
        perl Makefile.PL
        make distdir
        cd Map-Metro-Plugin-Map-Berlin-*
        cpanm --quiet --installdeps --notest .
        perl Makefile.PL
        make all test
